import type {Metadata} from 'next';

import {AppProps} from 'next/app';
import {ThemeProvider} from '@mui/material/styles';
import CssBaseline from '@mui/material/CssBaseline';
import {EmotionCache} from '@emotion/react';
import theme from '@/config/theme';

interface MyAppProps extends AppProps {
  emotionCache?: EmotionCache;
  children: React.ReactNode;
}

import {Inter} from 'next/font/google';
import 'leaflet/dist/leaflet.css';
import NextAuthSessionProvider from '@/providers/sessionProvider';

const inter = Inter({subsets: ['latin']});

export const metadata: Metadata = {
  title: 'Dashboard',
  description: 'Generated by create next app',
};

export default function RootLayout({children}: MyAppProps) {
  return (
    <html lang='pt-br'>
      <NextAuthSessionProvider>
        <ThemeProvider theme={theme}>
          <CssBaseline />
          <body className={inter.className}>{children}</body>
        </ThemeProvider>
      </NextAuthSessionProvider>
    </html>
  );
}
